# Configuración de la base de datos (Aiven)
spring.datasource.url=jdbc:mysql://data-base-libros-avilaramirezluiseduardo1-aa41.d.aivencloud.com:28453/Database_Libros
spring.datasource.username=David
spring.datasource.password=AVNS_o5MFw9o8l5LLBP4WoML
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de JPA / Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.format_sql=true

# SOLUCIÓN PARA RENDER (Bucle de redirecciones)
server.port=8080
server.forward-headers-strategy=framework
server.tomcat.remote-ip-header=x-forwarded-for
# CORREGIDO: Se agregó la 'o' al final
server.tomcat.protocol-header=x-forwarded-proto

# Seguridad extra para que Spring no intente forzar SSL interno
server.ssl.enabled=false

